IMPORTING LIBRARIES

In [ ]:
import numpy as np
import pandas as pd


IMPORTING DATASET 

In [ ]:
dataset=pd.read_csv('/content/weather AUS.csv')
X=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y=dataset.iloc[:,-1].values
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  01-12-2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  02-12-2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  03-12-2008   Albury     12.9     25.7       0.0          NaN       NaN   
3  04-12-2008   Albury      9.2     28.0       0.0          NaN       NaN   
4  05-12-2008   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['MelbourneAirport' 10.6 17.9 ... 13.5 13.4 'No']
 ['MelbourneAirport' 6.8 17.9 ... 12.6 16.5 'Yes']
 ['Me' nan nan ... nan nan nan]]


In [ ]:
print(Y)

['No' 'No' 'No' ... 'Yes' 'Yes' nan]


In [ ]:
Y=Y.reshape(-1,1)

In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['Yes']
 ['Yes']
 [nan]]


DEALING WITH INVALID DATASET 

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['MelbourneAirport' 10.6 17.9 ... 13.5 13.4 'No']
 ['MelbourneAirport' 6.8 17.9 ... 12.6 16.5 'Yes']
 ['Me' 17.2 20.0 ... 19.0 18.4 'No']]


In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['Yes']
 ['Yes']
 ['No']]


ENCODING DATASET

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,0]=le1.fit_transform(X[:,0])
le2=LabelEncoder()
X[:,4]=le2.fit_transform(X[:,4])
le3=LabelEncoder()
X[:,6]=le3.fit_transform(X[:,6])
le4=LabelEncoder()
X[:,7]=le4.fit_transform(X[:,7])
le5=LabelEncoder()
X[:,-1]=le5.fit_transform(X[:,-1])
le6=LabelEncoder()
Y=le6.fit_transform(Y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(X)

[[0 13.4 22.9 ... 16.9 21.8 0]
 [0 7.4 25.1 ... 17.2 24.3 0]
 [0 12.9 25.7 ... 21.0 23.2 0]
 ...
 [8 10.6 17.9 ... 13.5 13.4 0]
 [8 6.8 17.9 ... 12.6 16.5 1]
 [7 17.2 20.0 ... 19.0 18.4 0]]


In [ ]:
print(Y)

[0 0 0 ... 1 1 0]


FEATURE SCALING

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [ ]:
print(X)

[[-1.65241321  0.30136859  0.08230131 ...  0.13255588  0.14260219
  -0.52899093]
 [-1.65241321 -0.63700768  0.40266732 ...  0.18184499  0.51896359
  -0.52899093]
 [-1.65241321  0.22317057  0.49003986 ...  0.80617367  0.35336457
  -0.52899093]
 ...
 [-0.48095301 -0.13654034 -0.64580324 ... -0.426054   -1.12197214
  -0.52899093]
 [-0.48095301 -0.73084531 -0.64580324 ... -0.57392132 -0.65528399
   1.89039159]
 [-0.62738554  0.89567356 -0.33999933 ...  0.47757963 -0.36924932
  -0.52899093]]


SPLITTING DATASET INTO TRAINING DATASET AND TEST DATASET 

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[ 0.83693971  0.97387158  0.46091568 ...  1.15119742  0.59423587
   1.89039159]
 [-0.77381806  1.30230328  0.97058887 ...  1.97268253  0.1727111
  -0.52899093]
 [ 0.98337223  0.37956661  0.19879804 ...  0.60901724  0.20282001
  -0.52899093]
 ...
 [ 1.56910233  1.3805013   0.65022287 ...  1.11833801  0.69961707
  -0.52899093]
 [ 1.56910233  0.08241413 -0.82054833 ... -0.22889757 -0.67033845
  -0.52899093]
 [-1.65241321 -0.48061164 -1.22828688 ... -1.08324209 -1.54349691
  -0.52899093]]


In [ ]:
print(Y_train)

[1 1 0 ... 0 0 1]


TRAINING MODEL

1.RANDOM FOREST TRAINING MODEL 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(X_train,Y_train)

0.9998067259373792

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
print(y_pred)

[0 0 0 ... 1 0 0]


In [ ]:
y_pred=le6.inverse_transform(y_pred)


In [ ]:
print(y_pred)

['No' 'No' 'No' ... 'Yes' 'No' 'No']


In [ ]:
print(Y_test)

[0 0 0 ... 1 0 0]


In [ ]:
Y_test=le6.inverse_transform(Y_test)

In [ ]:
print(Y_test)

['No' 'No' 'No' ... 'Yes' 'No' 'No']


In [ ]:
Y_test=Y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)

In [ ]:
df=np.concatenate((Y_test,y_pred),axis=1)
dataframe=pd.DataFrame(df,columns=['rain on tommorrow','prediction of rain'])

In [ ]:
print(df)

[['No' 'No']
 ['No' 'No']
 ['No' 'No']
 ...
 ['Yes' 'Yes']
 ['No' 'No']
 ['No' 'No']]


In [ ]:
print(dataframe)

      rain on tommorrow prediction of rain
0                    No                 No
1                    No                 No
2                    No                 No
3                    No                 No
4                   Yes                Yes
...                 ...                ...
12930                No                 No
12931                No                 No
12932               Yes                Yes
12933                No                 No
12934                No                 No

[12935 rows x 2 columns]


In [ ]:
dataframe.to_csv('prediction.csv')

In [ ]:
dataframe=pd.read_csv('/content/prediction.csv')
dataframe

Unnamed: 0 rain on tommorrow prediction of rain
0               0                No                 No
1               1                No                 No
2               2                No                 No
3               3                No                 No
4               4               Yes                Yes
...           ...               ...                ...
12930       12930                No                 No
12931       12931                No                 No
12932       12932               Yes                Yes
12933       12933                No                 No
12934       12934                No                 No

[12935 rows x 3 columns]

CALCULATING ACCURACY

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)*100

84.5844607653653

2. LOGISTIC REGRESSION TRAINING MODEL

In [ ]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0).fit(X_train,Y_train)
classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_pred=clf.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
print(type(y_pred))

<class 'numpy.ndarray'>


In [ ]:
Y_test

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['Yes'],
       ['No'],
       ['No']], dtype=object)

In [ ]:
print(type(Y_test))

<class 'numpy.ndarray'>


In [ ]:
Y_test=le6.fit_transform(Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(Y_test)

[0 0 0 ... 1 0 0]


CALCULATING ACCURACY

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
confusion_matrix(Y_test,y_pred)

array([[9528,  527],
       [1665, 1215]])

In [ ]:
#accuracy score =(TP=TN)/(TP+TN+FP+FN)*100
(4892+593)/(4892+593+262+764)*100

84.24205191214867

In [ ]:
accuracy_score(Y_test,y_pred)*100


83.05373018940858

3. DECISION TREE TRAINING MODEL

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(random_state=0)
clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=0)

In [ ]:
y_pred=clf.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
Y_test

array([0, 0, 0, ..., 1, 0, 0])

CALCULATING ACCURACY

In [ ]:
accuracy_score(Y_test,y_pred)*100

77.27097023579435

4. KNN TRAINING MODEL

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh=KNeighborsClassifier(n_neighbors=5)
neigh.fit(X,Y)

KNeighborsClassifier()

In [ ]:
y_pred=neigh.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
Y_test

array([0, 0, 0, ..., 1, 0, 0])

CALCULATING ACCURACY

In [ ]:
accuracy_score(Y_test,y_pred)*100

87.20525705450328